### ISSUE TITLE
topk_indices = topk_indices // num_classes Killed

### ISSUE THREAD

**Issue by xiaotiancai899** [JonasSchult/Mask3D#107]
When I do the testing with dataset scannet200, the procedure would be killed. Can anyone help me with it? Thanks in advance!!!
The command I used is like this:
python main_instance_segmentation.py general.experiment_name="scannet200_val_query_${CURR_QUERY}_topk_${CURR_TOPK}_dbscan_${CURR_DBSCAN}" general.project_name="scannet200_val" general.checkpoint="saved/scannet200/last.ckpt" data/datasets=scannet200 general.num_targets=201 data.num_labels=200 general.eval_on_segments=true general.train_on_segments=true general.train_mode=false model.num_queries=${CURR_QUERY} general.topk_per_image=${CURR_TOPK} general.use_dbscan=true general.dbscan_eps=${CURR_DBSCAN}
And at the 104/312, the procedure was killed.

Testing DataLoader 0:  33%|█████████████▌                           | 103/312 [10:52<22:04,  6.34s/it]/home/pub-7/Documents/Mask3D/trainer/trainer.py:599: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  topk_indices = topk_indices // num_classes
Testing DataLoader 0:  33%|█████████████▋                           | 104/312 [11:10<22:21,  6.45s/it]/home/pub-7/Documents/Mask3D/trainer/trainer.py:599: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  topk_indices = topk_indices // num_classes
Killed

**Comment by xiaotiancai899** [comment]
@JonasSchult

**Comment by linwei0763** [comment]
Similar issue occured to me.

**Comment by JonasSchult** [comment]
Hi!
The warning regarding topk_indices is just a warning and should not result in a killed process.
I occured similar issues if the memory (RAM) was not sufficient. Can you monitor the memory consumption during evaluation and report if it uses up all memory?

Best,
Jonas

**Comment by xiaotiancai899** [comment]
> 

If not use dbscan postprocessing, there is no error using leaner version of testing like 'python main_instance_segmentation.py \
general.experiment_name="leaner_version_scannet200_val" \
general.project_name="scannet200_eval" \
general.checkpoint="checkpoints/scannet200/scannet200_val.ckpt" \
data/datasets=scannet200 \
general.num_targets=201 \
data.num_labels=200 \
general.eval_on_segments=true \
general.train_on_segments=true \
general.train_mode=false'
Is it OK to test it using leaner version? And what is the diference between these two methods?

**Comment by JonasSchult** [comment]
Running DBSCAN postprocessing results in better performance but introduces additional runtime/memory cost.

It is basically a trade-off.

Best,
Jonas
