### ISSUE TITLE
where the files after training are put?

### ISSUE THREAD

**Issue by xiaotiancai899** [JonasSchult/Mask3D#108]
I have already accomplished training and testing procedures. And next step I wanna see the segmentation results, but I cannot find the exact files to achieve visualization. How can I do that? Any ideas? Thanks in advance!!!

**Comment by xiaotiancai899** [comment]
@JonasSchult @francisengelmann @eltociear

**Comment by Raildex-wang** [comment]
I have the same problem

**Comment by JonasSchult** [comment]
Hi!

Logs are saved in the `saved/{experiment_name}` folder. If you set `--general.save_visualizations=true` during evaluation, You will also save all visualizations in this folder.

Best,
Jonas
