### ISSUE TITLE
Compile MinkowskiEngine Error

### ISSUE THREAD

**Issue by Wind-Wing** [JonasSchult/Mask3D#115]
Compile MinkowskiEngine will raise "No such file <cblas.h>" error in Ubuntu with AMD cpu.
`# sudo apt-get install libopenblas-dev` can solve this issue. Please update Readme.

**Comment by JonasSchult** [comment]
Thanks for your input!
I will update the README.

Best,
Jonas

**Comment by Vinit2244** [comment]
I also encountered the same error while compiling MinkowskiEngine. Specs of my system architecture is given below:

```text
Architecture:             x86_64
  CPU op-mode(s):         32-bit, 64-bit
  Address sizes:          46 bits physical, 48 bits virtual
  Byte Order:             Little Endian
CPU(s):                   16
  On-line CPU(s) list:    0-15
Vendor ID:                GenuineIntel
  Model name:             Intel(R) Xeon(R) W-2245 CPU @ 3.90GHz
    CPU family:           6
    Model:                85
```

So I think the error is not specific to AMD cpu.
It got solved using `sudo apt-get install libopenblas-dev`. Please update the README @JonasSchult.
