### ISSUE TITLE
Can the training be conducted on single 3090ti gpu?

### ISSUE THREAD

**Issue by Pixie412** [JonasSchult/Mask3D#127]
Hi,

Thanks for releasing code. I am wondering if the training can be conducted on a 3090ti (24G memory)?

**Comment by JonasSchult** [comment]
Hi!

Networks trained on 2cm voxelization unfortunately need more than 24GB RAM.
You can set `data.voxel_size=0.05` but this will result in worse performance.

Best,
Jonas
