### ISSUE TITLE
STPLS3D implementation

### ISSUE THREAD

**Issue by meidachen** [JonasSchult/Mask3D#13]
Thanks for benchmarking on STPLS3D, and congrats on achieving state-of-the-art performance! We are looking forward to your scripts for STPLS3D.

**Comment by JonasSchult** [comment]
Hi Meida,

thanks for your kind words! :) 

we have just released the code for supporting STPLS3D. You can find the corresponding scripts [here](https://github.com/JonasSchult/Mask3D/tree/main/scripts/stpls3d).

Best,
Jonas

**Comment by meidachen** [comment]
Thanks, Jonas; I have updated the STPLS3D repo to point readers to check out the Mask3D repo for implementation details and the pre-trained model.
