### ISSUE TITLE
effect of shared_decoder

### ISSUE THREAD

**Issue by lx709** [JonasSchult/Mask3D#133]
Hello @JonasSchult ,  Thanks for sharing the code of your nice work. I'm just wondering if you have checked the effect of using shared decoder transformer layers. Let's say will the performance decrease if we set shared_decoder=False.

**Comment by JonasSchult** [comment]
Hi!
Great question.
In my experiments, the effect was rather minimal while saving quite some memory.

Best,
Jonas

**Comment by lx709** [comment]
Thanks for your quick response, much appreciate that.
