### ISSUE TITLE
About the loss in train

### ISSUE THREAD

**Issue by windfill** [JonasSchult/Mask3D#137]
Thanks for your great work and release the code！
I would be grateful if you could provide the loss log during the training process of the s3dis data set or other datasets.
On my custom data set, the final loss is still very large.

Epoch 598:  66%|██████▋   | 265/400 [08:19<04:14,  1.88s/it, loss=20.2, v_num=rain]
Epoch 598:  66%|██████▋   | 266/400 [08:21<04:12,  1.88s/it, loss=20.2, v_num=rain]
Epoch 598:  66%|██████▋   | 266/400 [08:21<04:12,  1.88s/it, loss=20.1, v_num=rain]
Epoch 598:  67%|██████▋   | 267/400 [08:22<04:10,  1.88s/it, loss=20.1, v_num=rain]
Epoch 598:  67%|██████▋   | 267/400 [08:22<04:10,  1.88s/it, loss=20.1, v_num=rain]
Epoch 598:  67%|██████▋   | 268/400 [08:24<04:08,  1.88s/it, loss=20.1, v_num=rain]
Epoch 598:  67%|██████▋   | 268/400 [08:24<04:08,  1.88s/it, loss=20.1, v_num=rain]
Epoch 598:  67%|██████▋   | 269/400 [08:26<04:06,  1.88s/it, loss=20.1, v_num=rain]
Epoch 598:  67%|██████▋   | 269/400 [08:26<04:06,  1.88s/it, loss=20.2, v_num=rain]
Epoch 598:  68%|██████▊   | 270/400 [08:28<04:04,  1.88s/it, loss=20.2, v_num=rain]
Epoch 598:  68%|██████▊   | 270/400 [08:28<04:04,  1.88s/it, loss=20.2, v_num=rain]
Epoch 598:  68%|██████▊   | 271/400 [08:30<04:03,  1.88s/it, loss=20.2, v_num=rain]
Epoch 598:  68%|██████▊   | 271/400 [08:30<04:03,  1.88s/it, loss=20.2, v_num=rain]
Epoch 598:  68%|██████▊   | 272/400 [08:32<04:01,  1.88s/it, loss=20.2, v_num=rain]

**Comment by windfill** [comment]
@JonasSchult

**Comment by Lizhinwafu** [comment]
Have you solved this issue?
