### ISSUE TITLE
Training on S3DIS

### ISSUE THREAD

**Issue by Giutear** [JonasSchult/Mask3D#15]
First of all, thank you for releasing your code to the public.

I'm currently trying to train the network from scratch on the S3DIS dataset and I noticed a mistake in the training script
https://github.com/JonasSchult/Mask3D/blob/0cb9a240d7b557e16a8216a300e8f71bc91fef3a/scripts/s3dis/s3dis_from_scratch.sh#L16
https://github.com/JonasSchult/Mask3D/blob/0cb9a240d7b557e16a8216a300e8f71bc91fef3a/scripts/s3dis/s3dis_from_scratch.sh#L30
the `data` struct does not have a field `is_scannet`.

My second question relates to out of memory errors. In your paper you state that you've used a GPU with 48 GB of memory. I currently only have access to a GPU with 24 GB of memory but thought I could counteract this by using a batch size of 1. However, after 7 epochs the training crashes with OOM. I noticed that each epoch increases the used memory slightly from initial 16 GB to the full 24 GB.  I did not modify your code apart from the changes to the `s3dis_from_scratch.sh`. Do you think this is due to memory fragmentation from the sparse backbone or could this be a memory leak?

I would really appreciate it if you could help me solve this issue.

**Comment by yrk-creator** [comment]
I have met the same problem, just  need to add a “+" before data.is_scannet=false
"+data.is_scannet=false"

**Comment by JonasSchult** [comment]
Hi,

`data.is_scannet` is a deprecated parameter. I removed the parameter from the scripts in the latest commit. Thanks for letting me know! :) 

Training on S3DIS is particularly challenging as some rooms are very large. We cropped 6m x 6m during training, but evaluated on full scenes.

I am unfortunately not sure why the training crashed after 7 epochs for you.

Best,
Jonas

**Comment by JonasSchult** [comment]
Hi,

yes, we do not use PointRend. Afaik, there exists no implementation of PointRend for 3D pointclouds. We didn't conduct experiments with it. It'll be very intersting to see if scores can be improved and/or memory consumption reduced with it. :)
