### ISSUE TITLE
The performance of pretrained model on S3DIS (area1)

### ISSUE THREAD

**Issue by xjdexjt** [JonasSchult/Mask3D#17]
Hi, I just use the pretrained model on S3DIS (area1) on my processed dataset using "Stanford3dDataset_v1.2_Aligned_Version" by running following script.
![image](https://user-images.githubusercontent.com/40589000/196361925-7f7605b3-bb95-4471-8bbb-89eb5e053adf.png)

The results are as follows, which is lower that the reported results a lot.
![14cca5f5ce20cb7cb68a8ba74cd446a](https://user-images.githubusercontent.com/40589000/196361282-e99b5d1d-7310-48d9-9408-af7150579361.jpg)

![image](https://user-images.githubusercontent.com/40589000/196362108-be9bffbf-727f-458e-8491-3548f2bd0c31.png)

**Comment by JonasSchult** [comment]
Hi,

I just reran the inference script on a newly processed s3dis dataset. I could reproduce the claimed scores.
Did you use the **non** aligned version of S3DIS?

Moreover, Area 1 contains 44 scenes but your log shows only 23 processed scans. I assume that something happened with your dataset.

Best,
Jonas

**Comment by xjdexjt** [comment]
@JonasSchult Thanks for your reply. I have another problem. I retrain the model on S3DIS. I observe the results of map/ap50/ap25 are close the reported results. But the result (30.1) on  mPrec is lower than expected result (68.7 in your paper) a lot. 

![image](https://user-images.githubusercontent.com/40589000/197563693-e42badd3-01e7-43ed-82db-ad172e3fbb67.png)
Should I set the filter_out_instances as True and other hyper-paramters (e.g., scores_threshold)?

Best.

**Comment by JonasSchult** [comment]
Hi!
Yes exactly please set `filter_out_instances=true` and `score_threshold=0.8`. We give some more explanations on page 5 in our paper.

Best,
Jonas

**Comment by peoplelu** [comment]
Hello，I want to know which device do you use when you train the model on s3dis？A100？And ，what is the consumption of  memory，48gb？Thank you very much.

**Comment by JonasSchult** [comment]
Hi!
I used a single A40 GPU with 48GB RAM.

**Comment by peoplelu** [comment]
> **non** aligned version of S3DIS

 Thank you very much! I also want to know which version of s3dis do you use, non aligned version or aligned?
