### ISSUE TITLE
Preprocessing data

### ISSUE THREAD

**Issue by Ritchizh** [JonasSchult/Mask3D#18]
Hi! I'm trying to run your preprocessing script for STPLS3D data and I've got an error:
_stpls3d_preprocessing.py: command not found_
I assume there's some problem with using Fire module.

In
```
datasets/preprocessing/stpls3d_preprocessing.py preprocess \
--data_dir="PATH_TO_STPLS3D" \
--save_dir="../../data/processed/stpls3d"
```
**are we calling for 'preprocess' function? Because it is present only in** [base_preprocessing.py](https://github.com/JonasSchult/Mask3D/blob/main/datasets/preprocessing/base_preprocessing.py) and [matterport_preprocessing.py](https://github.com/JonasSchult/Mask3D/blob/main/datasets/preprocessing/matterport_preprocessing.py) but there's no such function in other datasets scripts.

**Comment by JonasSchult** [comment]
Hi! :)

I just fixed the readme instructions about preprocessing.

You need to put `python` in front.

```
python datasets/preprocessing/stpls3d_preprocessing.py preprocess \
--data_dir="PATH_TO_STPLS3D" \
--save_dir="../../data/processed/stpls3d"
```

Thanks for bringing this up!

Best,
Jonas

**Comment by Ritchizh** [comment]
@JonasSchult 
Thank you for your fast reply! 
You might also need to include _pandas_ and _natsort_ in the list of pip packages - they weren't installed :)

**Comment by Ritchizh** [comment]
Preprocessing script for STPLS3D data works. Thank you.
