### ISSUE TITLE
Mask3D Installation: dependencies versions compatibility

### ISSUE THREAD

**Issue by Ritchizh** [JonasSchult/Mask3D#19]
Hi! I'm trying to run [stpls3d_val.sh](https://github.com/JonasSchult/Mask3D/blob/main/scripts/stpls3d/stpls3d_val.sh) - inference on STPLS3D with the pretrained checkpoint.

_ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
detectron2 0.6 requires hydra-core>=1.1, but you have hydra-core 1.0.5 which is incompatible.
detectron2 0.6 requires iopath<0.1.10,>=0.1.7, but you have iopath 0.1.10 which is incompatible.
detectron2 0.6 requires omegaconf>=2.1, but you have omegaconf 2.0.6 which is incompatible._

I have installed detectron2 as in the instruction:
`pip install 'git+https://github.com/facebookresearch/detectron2.git@710e7795d0eeadf9def0e7ef957eea13532e34cf' --no-deps`
In the requirement.txt the following packages versions are specified: 
hydra-core==1.0.5, iopath==0.1.9, omegaconf==2.0.6

**Maybe some other version of detectron2, than given in the installation guide, needs to be installed to be compatible with the rest of the packages?**

**Comment by JonasSchult** [comment]
Hi!

Yes there is an incompatibility pip complains about. However, it is possible to install the incompatible packages nonetheless.
I agree that this is quite ugly at the moment. However, the environment works.

Best,
Jonas
