### ISSUE TITLE
Project page is "404"

### ISSUE THREAD

**Issue by weiguangzhao** [JonasSchult/Mask3D#2]
Hey guys, I find your project page is 404:"https://jonasschult.github.io/Mask3D/". I also can't find the paper and youtube video, is there any thing wrong? I think this is a good work, when will it be released? Thank you.

**Comment by JonasSchult** [comment]
Hi Weiguang,

thank you a lot for your interest in our work!

We are currently working on a big release including more datasets, improved results and releasing the code.
We will reuse this repository, so please stay tuned! The release is planned next month.

Best,
Jonas
