### ISSUE TITLE
Does this work on meshes only or can it work with an unorganized RGBXYZ Pointcloud?

### ISSUE THREAD

**Issue by soulslicer** [JonasSchult/Mask3D#23]
I would also like to know what kind of runtime performance we get with this

**Comment by JonasSchult** [comment]
Hi!
It also works on point clouds. Please refer to the sample scripts for STPLS3D and S3DIS.
Please see Table 1 in our [paper](https://arxiv.org/pdf/2210.03105.pdf) regarding the runtime.

Best,
Jonas

**Comment by yrk-creator** [comment]
Hi! When I experiments on ScanNet dataset, I'm curious whether the segment information on the 3rd axis of labels can help boost the  performance, how does it work? Thank you!

**Comment by JonasSchult** [comment]
Hi!

Segments may be helpful to introduce geometric low-pass filtering. When points are aggregated into meaningful segments, we may reduce high-frequency noise.

Best,
Jonas
