### ISSUE TITLE
Missing backbone checkpoint file?

### ISSUE THREAD

**Issue by Bitfultea** [JonasSchult/Mask3D#24]
Thanks for releasing this repo! 
I am try to write a interfacing code based on this repo and I found I couldn't load the backbone checkpoint using the provided checkpoint?  Does it need a independent checkpoint file for backbone?

**Comment by JonasSchult** [comment]
Hi!
An interface to Mask3D sounds like a great idea! :)
The backbone is included in the checkpoint file. Can you give me more details?

Best,
Jonas

**Comment by Bitfultea** [comment]
Hi
I made a mistake of using the Scannet dataset config for S3dis dataset. I now can load the full model weights. Thanks for the quick response.
