### ISSUE TITLE
How to process the data for Scannet200?

### ISSUE THREAD

**Issue by yichaoshen-MS** [JonasSchult/Mask3D#25]
I should preprocess scannet200 in this scannet200-original Repostitory(LanguageGroundedSemseg,https://github.com/RozDavid/LanguageGroundedSemseg)  or the Repostitory（scannet :[https://github.com/ScanNet/ScanNet/blob/master/BenchmarkScripts/ScanNet200/preprocess_scannet200.py）](https://github.com/ScanNet/ScanNet/blob/master/BenchmarkScripts/ScanNet200/preprocess_scannet200.py%EF%BC%89)?

**Comment by JonasSchult** [comment]
Hi,
please use the preprocessing script from our repository. See here: https://github.com/JonasSchult/Mask3D#scannet--scannet200

Best,
Jonas
