### ISSUE TITLE
What does the "label==253" mean?

### ISSUE THREAD

**Issue by yichaoshen-MS** [JonasSchult/Mask3D#27]
Hello,
I would like to ask the means of "label==253", because I found some examples' ground truth has the label which is named as 253, and it is out of the number of classes in dataset.

**Comment by JonasSchult** [comment]
Hey,
this is the `ignore_class`. Loss won't be calculated for this instance.

Best,
Jonas

**Comment by yichaoshen-MS** [comment]
> Hey, this is the `ignore_class`. Loss won't be calculated for this instance.
> 
> Best, Jonas

Thanks
