### ISSUE TITLE
What does the 3rd labels of point mean in instance segments?

### ISSUE THREAD

**Issue by yichaoshen-MS** [JonasSchult/Mask3D#29]
I found there is a 3-dims labels per point, first is the class-id, the second is instance-id, but I don't know the 3rd dim means.
I guess it may be able to be named as "segment-id". because it usually generates items like "point2segment","segment2label". 
So, what does the 3rd dim in point's labels mean, or what does the segment represent?

**Comment by JonasSchult** [comment]
Hi!

Yes, you are right. This column is used for the segment id (if provided). Find more details [here](https://github.com/JonasSchult/Mask3D#scannet--scannet200).

Best,
Jonas

**Comment by lyf6** [comment]
@yichaoshen-MS what does segment id mean?
