### ISSUE TITLE
How to test the model in Scannet and Scannet200 dataset benchmark?

### ISSUE THREAD

**Issue by yichaoshen-MS** [JonasSchult/Mask3D#30]
Hi, I have finished the train and  test in scannet200. However, when I attempt to submit the output in "eval_output/" to the official website of scannet, it recalled back that the format is error.

**Comment by JonasSchult** [comment]
Hi!

You need to create a zip from the output. Make sure that the root directory is not included in the zip.

Please let me know if you need more info. :)

Best,
Jonas
