### ISSUE TITLE
Potential bug with label_offset during evaluation of Scannet200

### ISSUE THREAD

**Issue by xuanlinli17** [JonasSchult/Mask3D#34]
During the data collation process [here](https://github.com/JonasSchult/Mask3D/blob/0e5c32e38e3a793907ede2e176820b53392ea971/datasets/utils.py#L404), the code subtracts `label_offset` from the remapped semantic id (i.e. the semantic id obtained after `_remap_from_zero` in [here](https://github.com/JonasSchult/Mask3D/blob/0e5c32e38e3a793907ede2e176820b53392ea971/datasets/semseg.py#L597)) and clamps the resulting semantic id to be at least zero. During the evaluation process [here](https://github.com/JonasSchult/Mask3D/blob/5581ccb6e4cc7dfb196ae1a9d1391d3c6add12f7/trainer/trainer.py#L583), the code adds `label_offset` back to the semantic id.

However, this poses an issue for Scannet200 since its ignored remapped semantic ids are `[0,2]` with `label_offset=2` (see [here](https://github.com/JonasSchult/Mask3D/blob/5581ccb6e4cc7dfb196ae1a9d1391d3c6add12f7/conf/data/datasets/scannet200.yaml#L32)). In Scannet200, `0` in the remapped semantic id corresponds to the wall, `1` the chair, and `2` the floor. When performing evaluation, the `1` of the chair will become `0` after subtracting `label_offset` and then clamping to be at least zero. It will then become `2` during evaluation after adding `label_offset` back to `0`, which causes the floor class to correspond to the chair class.

**Comment by JonasSchult** [comment]
Hi Xuanlin!

Thanks for your interest in our work!

Admittedly, the `label_offset` strategy is quite complicated and for sure, can be improved. You are right. You need to take special provisions in order to make it work for ScanNet200. [Here](https://github.com/JonasSchult/Mask3D/blob/main/trainer/trainer.py#L578), we take care of the floor class problem.

Best,
Jonas
