### ISSUE TITLE
ModuleNotFoundError: No module named 'datasets.preprocessing'

### ISSUE THREAD

**Issue by xiaotiancai899** [JonasSchult/Mask3D#37]
ModuleNotFoundError: No module named 'datasets.preprocessing'
How to fix this error?

**Comment by danlapko** [comment]
add empty __init__.py to datasets/ and to datasets/preprocessing.

**Comment by danlapko** [comment]
And run code using `-m` flag. E.g.: `python -m datasets.preprocessing.scannet_preprocessing preprocess --data_dir=...`

**Comment by xiaotiancai899** [comment]
It worked, thank you very much.
