### ISSUE TITLE
Ansicht der Publikation

### ISSUE THREAD

**Issue by Fan-QY** [JonasSchult/Mask3D#4]
Hallo Jonas,

Zunächst Herzlichen Glückwunsch zu Ihrer hervorragenden Arbeit!

Ihre WebSeit-Publikation kann nicht geöffnet werden. Wie kann ich das lesen? 

Wenn Sie mir sagen könnten, würde ich sehr freuen, was Ihre speziellen Trainingsgeräte sind und wie lange Sie für das Training brauchen? Wie viel RAM haben Sie? Welche Grafikkarten wurden verwendet und wie viele Karten wurden insgesamt eingesetzt?

Und werden Sie einen Leitfaden für die Training von S3DIS (from scratch) auf herausgeben? Wann wird sie verfügbar sein?

Beste Grüße

——————————————————————————————————
Hello Jonas,

First of all congratulations for your excellent work!

Your webpage publication can not be opened. How can I read it? 

If you could tell me, I would be very happy to know what your special training equipment is and how long it takes you to train? How much RAM do you have? What graphics cards were used and how many cards were used in total?

And will you release a guide for training S3DIS (from scratch) on? When will it be available?

Best regards

**Comment by JonasSchult** [comment]
Hi Qinyuan,

thank you for your kind words. You can access the project page [here](https://jonasschult.github.io/Mask3D/). We currently prepare to publish the paper. 
So please stay tuned! :)

About your questions regarding training:
- It takes roughly 78h on a single A40 to train the best ScanNet model on 2cm voxelization. Time and hardware requirements reduce drastically if you train with 5cm voxelization (although with a performance drop).
- RAM for training is not a limiting factor. If you have more than 16GB, you should be able to train the model.
 
Here is a [guide/script for training S3DIS](https://github.com/JonasSchult/Mask3D/blob/main/scripts/s3dis/s3dis_from_scratch.sh).
Remember to preprocess the dataset first, as described below:

```
datasets/preprocessing/s3dis_preprocessing.py preprocess \
--data_dir="PATH_TO_Stanford3dDataset_v1.2" \
--save_dir="../../data/processed/s3dis"
```

Best,
Jonas

**Comment by JonasSchult** [comment]
Hi Qinyuan,

you find the [paper link](https://arxiv.org/abs/2210.03105) in the readme now. :)

Best,
Jonas
