### ISSUE TITLE
ScanNet200 Floor and wall 

### ISSUE THREAD

**Issue by faad3** [JonasSchult/Mask3D#42]
Hello!

When I'm evaluating on ScanNet200, the outputs don't include floor and wall classes. How can this problem be solved?

**Comment by JonasSchult** [comment]
Hi Danila,

thanks for your interest in our project! :)

Mask3D tackles semantic *instance* segmentation on 3D point clouds. In the [official benchmark](https://kaldir.vc.in.tum.de/scannet_benchmark/scannet200_semantic_instance_3d), `floor` and `wall` are not treated as instances. Therefore, we exclude them.

However, including these classes is technically possible. You would need to adapt the data loader and config files to treat `floor` and `wall` as valid classes.
Tip: In S3DIS, they are valid classes. You can get inspiration there.

Let me know if you have any further questions.

Best,
Jonas

**Comment by faad3** [comment]
Everything is clear, thank you!

**Comment by lionlai1989** [comment]
Hi @faad3,

I am encountering the same issue as yours here. Could you please show me what changes you made to make it work with "floor" and "wall"?

Thank you.

**Comment by lionlai1989** [comment]
Hi,

I have another question. Do I need to retrain the model with the ScanNet200 dataset if I want to include classes, "wall" and "floor"?

Is it possible to only modify the inference code to make the model provided by Mask3D be able to generate the classes "wall" and "floor"?

Thank you.

**Comment by JonasSchult** [comment]
Hi!
The model is not trained to segment wall and floor.
You need to retrain the model.

Best,
Jonas

**Comment by lionlai1989** [comment]
Thank you for clarification.

Best,
