### ISSUE TITLE
Cuda Version Compatibility

### ISSUE THREAD

**Issue by CharlesCai123** [JonasSchult/Mask3D#44]

**Comment by CharlesCai123** [comment]
Hello, I notice that in your readme the cuda version is 11.6, so on my platform is 11.4, does it work for the code too?

**Comment by JonasSchult** [comment]
Hi Charles,

I tested the code on several systems. I am quite confident that it will work. Make sure to install the correct dependencies.
Let me know if you need help!

Best,
Jonas
