### ISSUE TITLE
Double random_cuboid usage

### ISSUE THREAD

**Issue by mariusud** [JonasSchult/Mask3D#48]
Hi and thanks for your code,
Could you clarify the use of random cuboid? I see that it is called once on points [here](https://github.com/JonasSchult/Mask3D/blob/main/datasets/semseg.py#L343) and once again [later](https://github.com/JonasSchult/Mask3D/blob/main/datasets/semseg.py#L364) on coordinates and labels, the latter of which inputs 3 arguments while your implementation of random cuboid only takes in 1

**Comment by JonasSchult** [comment]
Hi Marius!

I see! It indeed does not seem intuitive and is unintended.
Thanks for pointing it out!

Best,
Jonas
