### ISSUE TITLE
Performance on Scannet V2

### ISSUE THREAD

**Issue by ssh10032** [JonasSchult/Mask3D#49]
Hello and Thanks for your great work.

I checked the performance by training mask 3D on ScanNet, and it is lower than the performance of the weight provided. 
I used the configuration with the weight provided( scripts/scannet/scannet_val.sh). 
Did I miss anything?

![image](https://user-images.githubusercontent.com/83348645/221387537-e38164f1-115c-4729-b055-8106bae7d73c.png)

**Comment by aiyouweiyxx** [comment]
hi, Have you solved this problem now?

**Comment by JonasSchult** [comment]
As this issue is stale, I will close it. Please feel free to open it again. :)

Best,
Jonas
