### ISSUE TITLE
How to train Mask3D with a custom dataset.

### ISSUE THREAD

**Issue by IvanGarcia7** [JonasSchult/Mask3D#50]
Hello.

I'm really interested to know how to train the model using my own pointcloud dataset, for my thesis. Can you provide some instructions about how to do that?

Thanks in advance!!

**Comment by JonasSchult** [comment]
Hi Ivan,

thanks for your interest in our work.
I unfortunately do not have detailed instructions to integrate new datasets in the Mask3D codebase.

I recommend to take a look into  the preprocessing folder ([here](https://github.com/JonasSchult/Mask3D/tree/main/datasets/preprocessing)) to see how we  preprocessed different datasets to a common format which we used in the rest of the codebase. If you write such a preprocessing script for your custom dataset, you can use it with Mask3D.

Let me know if you have any further questions! :) 

Best,
Jonas
