### ISSUE TITLE
about s3dis conf

### ISSUE THREAD

**Issue by liujingangel** [JonasSchult/Mask3D#53]
Hello, thans for your work!  when I learn the s3dis config to train model on  my custom data, I'm confused  why "data.num_labels(13)" is less than "general.num_targets(14)", and other datasets equal.
https://github.com/JonasSchult/Mask3D/blob/b60b143ceca2e372bac9147d112af1dc6dccb7d3/scripts/s3dis/s3dis_from_scratch.sh#L14

can you please help me with this confusion?
thanks in advance

**Comment by JonasSchult** [comment]
Hi!

thanks for your interest in our work!

In S3DIS, every point is associated with an instance (e.g. `wall`, `floor` are instances in S3DIS).
This is in contrast to ScanNet, where `wall`, and `floor` are not treated as instances.

In particular for S3DIS, we have 13 classes but use `14` targets (+1 for the no-instance semantic class).

Best,
Jonas
