### ISSUE TITLE
already trained modle?

### ISSUE THREAD

**Issue by xiaotiancai899** [JonasSchult/Mask3D#55]
Is the model already trained? Do I need to train after I download it or can I just use it without training it at first?

**Comment by JonasSchult** [comment]
Hi!
We provide checkpoints for all trained models. You can find them [here](https://omnomnom.vision.rwth-aachen.de/data/mask3d/checkpoints/).
In the folder `scripts` you find scripts how to evaluate the model using the pre-trained weights.

Best,
Jonas
