### ISSUE TITLE
Does Mask3D support direct training and inference for large scenes?

### ISSUE THREAD

**Issue by Fan-QY** [JonasSchult/Mask3D#6]
Hallo. Congratulations again on your excellent work.

If my own dataset is a training scenario of 5 to 40 million points, does Mask3D support it?
I can convert my data structure to the same type of data structure as the S3DIS data, is there anything I should be aware of in the case of such mega scenes?

**Comment by JonasSchult** [comment]
Hi! :)

For S3DIS, we ran into a similar challenge like you do right now. Here, a few scenes are quite large (e.g. lecture halls).
During training, we used random crops from the ground plane of maximal size 6m x 6m ([here](https://github.com/JonasSchult/Mask3D/blob/main/datasets/semseg.py#L210) and [here](https://github.com/JonasSchult/Mask3D/blob/main/conf/data/indoor.yaml#L43)).
During inference, we could process the full scenes and did not have to resort to cropping.

Let me know if you need some more info!

Best,
Jonas

**Comment by Fan-QY** [comment]
> 



> 你好！:)
> 
> 对于 S3DIS，我们遇到了与您现在类似的挑战。在这里，一些场景相当大（例如演讲厅）。 在训练期间，我们使用了最大尺寸为 6m x 6m（[此处](https://github.com/JonasSchult/Mask3D/blob/main/datasets/semseg.py#L210)和[此处](https://github.com/JonasSchult/Mask3D/blob/main/conf/data/indoor.yaml#L43)）的地平面的随机作物。 在推理过程中，我们可以处理整个场景，而不必进行裁剪。
> 
> 如果您需要更多信息，请告诉我！
> 
> 最好的， 乔纳斯



> Hi! :)
> 
> For S3DIS, we ran into a similar challenge like you do right now. Here, a few scenes are quite large (e.g. lecture halls). During training, we used random crops from the ground plane of maximal size 6m x 6m ([here](https://github.com/JonasSchult/Mask3D/blob/main/datasets/semseg.py#L210) and [here](https://github.com/JonasSchult/Mask3D/blob/main/conf/data/indoor.yaml#L43)). During inference, we could process the full scenes and did not have to resort to cropping.
> 
> Let me know if you need some more info!
> 
> Best, Jonas
Hallo! Thank you for your kind reply.
My scenario is a whole building, so they are bigger in size.
I have tried using softgroups for training and inference before, but although I was able to train with the appropriate processing, I was not able to infer.
So I was thinking of a way to make it possible to retain as much information as possible while accomplishing the inference task with as much accuracy as possible.
I saw the early SEGCloud process, and since its code is not open source, I have tried to reproduce the "voxel-based downsampling (preprocess)" and "trilinear interpolation" myself, but due to the voxel but the performance of the algorithm will be lost due to the voxels.
So I would prefer an end-to-end instance partitioning algorithm for very large scenes to handle my own scenes, do you have any suggestions for a solution?
![image](https://user-images.githubusercontent.com/58989572/194335887-5a0b0a48-4e88-4927-af16-9c5bc8bbe9ba.png)
