### ISSUE TITLE
Training on multiple GPUs

### ISSUE THREAD

**Issue by LinLin1031** [JonasSchult/Mask3D#60]
Hello!

I would like to ask a question. Is it possible to do your work on multiple GPUs at the same time?

I have three 16GB GPUs here and I would like to train on all three GPUs at the same time so that I can maybe achieve better results.
If it is possible, can you give me some suggestions for modifying the code?

Best.

**Comment by JonasSchult** [comment]
Hi!

Right now, the codebase does not support multi-gpu training.
It sounds like a great extension! :)

Best,
Jonas
