### ISSUE TITLE
Problems encountered during Training S3DIS data set?

### ISSUE THREAD

**Issue by hanbinbin-web** [JonasSchult/Mask3D#65]
Hello, thank you for your work. In the process of training s3dis data set, I encountered the following problems. Can you explain the relevant reasons?

![image](https://user-images.githubusercontent.com/67538618/234589153-aada3a4b-27c9-4e13-8ebf-0f7326fa02c0.png)

**Comment by JonasSchult** [comment]
Hi!
Thanks for your interest in our work! :)

We have seen similar errors with newer python environments.
Please check out [this pull request](https://github.com/JonasSchult/Mask3D/pull/51). Let me know if it solves your issue.

Best,
Jonas

**Comment by hanbinbin-web** [comment]
I have checked and it is indeed an environmental problem. Thank you for your reply.
