### ISSUE TITLE
wandb: ERROR Error while calling W&B API: entity schult not found during upsertBucket (<Response [404]>)

### ISSUE THREAD

**Issue by xiaotiancai899** [JonasSchult/Mask3D#66]
EXPERIMENT ALREADY EXIST
{'_target_': 'pytorch_lightning.loggers.WandbLogger', 'project': '${general.project_name}', 'name': '${general.experiment_name}
', 'save_dir': '${general.save_dir}', 'entity': 'schult', 'resume': 'allow', 'id': '${general.experiment_name}'}
wandb: Currently logged in as: zjp2023. Use `wandb login --relogin` to force relogin
wandb: ERROR Error while calling W&B API: entity schult not found during upsertBucket (<Response [404]>)
Problem at: /home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/pytorch_lightning/loggers/wandb.py 405 experiment
Error executing job with overrides: ['general.checkpoint=/mnt/d:/student/Documents/software/wsl/mask3d/Mask3D_main/Mask3D_main/
ckpt/scannet200_val.ckpt', 'general.train_mode=false']
Error in call to target 'pytorch_lightning.loggers.wandb.WandbLogger':
CommError('It appears that you do not have permission to access the requested resource. Please reach out to the project owner t
o grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404:
 Not Found)')
full_key: logging0

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

How to solve this problem? Thanks a lot!

**Comment by Vishal1711** [comment]
I think by changing `'entity': 'schult'` with your corresponding wand entity name, that is, zjp2023's, the problem should get solved.

**Comment by xiaotiancai899** [comment]
> 

logging:
- _target_: pytorch_lightning.loggers.WandbLogger
  project: ${general.project_name}
  name: ${general.experiment_name}
  save_dir: ${general.save_dir}
  entity: zjp2023
  resume: allow
  id: ${general.experiment_name}

I have already changed the entity name to 'zjp2023'. But the same error still happens.

EXPERIMENT ALREADY EXIST
{'_target_': 'pytorch_lightning.loggers.WandbLogger', 'project': '${general.project_name}', 'name': '${general.experiment_name}', 'save_dir': '${general.save_dir}', 'entity': 'schult', 'resume': 'allow', 'id': '${general.experiment_
name}'}
wandb: Currently logged in as: zjp2023. Use `wandb login --relogin` to force relogin
wandb: ERROR Error while calling W&B API: entity schult not found during upsertBucket (<Response [404]>)
Problem at: /home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/pytorch_lightning/loggers/wandb.py 405 experiment
Error executing job with overrides: []
Error in call to target 'pytorch_lightning.loggers.wandb.WandbLogger':
CommError('It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networ
king setup.(Error 404: Not Found)')
full_key: logging0

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by JonasSchult** [comment]
Hi!

Please change the experiment name to some new and unique name, e.g., `general.experiment_name="NEW_UNIQUE_EXPERIMENT_NAME"`.

As the experiment already exists, the codebase tries to resume by loading old settings, e.g. the wandb account which is still set to `schult`.

Best,
Jonas

**Comment by xiaotiancai899** [comment]
Thanks a lot. It sounds like good advice. But could you please tell me how can I change the experiment name? Just like in which file inside the module. Cause I am a little confused. Appreciate it.

**Comment by JonasSchult** [comment]
Hi!
No worries! :) 

you can easily change the experiment name using the command line interface:

```
python main_instance_segmentation.py \
general.experiment_name="YOUR_NEW_NAME"
```

Check [this](https://github.com/JonasSchult/Mask3D/blob/main/scripts/scannet200/scannet200_val.sh#L9) out to get some inspiration which parameters you can set.

Best,
Jonas

**Comment by xiaotiancai899** [comment]
Thanks. And how to change the entity name?

**Comment by xiaotiancai899** [comment]
I tried to set the new experiment name using the command line. But the same error happens. And it seems the entity 'schult' still not be changed. 


python main_instance_segmentation.py \
> general.experiment_name="zjp2023_scannet200_val"
/mnt/d/student/Documents/software/wsl/mask3d/mask3d_main/mask3d_main/main_instance_segmentation.py:64: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  @hydra.main(config_path="conf", config_name="config_base_instance_segmentation.yaml")
/mnt/d/student/Documents/software/wsl/mask3d/mask3d_main/mask3d_main/main_instance_segmentation.py:84: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  @hydra.main(config_path="conf", config_name="config_base_instance_segmentation.yaml")
/mnt/d/student/Documents/software/wsl/mask3d/mask3d_main/mask3d_main/main_instance_segmentation.py:97: UserWarning:
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  @hydra.main(config_path="conf", config_name="config_base_instance_segmentation.yaml")
/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'config_base_instance_segmentation.yaml': Defaults list is missing `_self_`. See https://hydra.cc/docs/1.2/upgra
des/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/hydra/core/default_element.py:124: UserWarning: In 'loss/set_criterion': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/changes_to_package_header for more information
  deprecation_warning(
/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/hydra/core/default_element.py:124: UserWarning: In 'matcher/hungarian_matcher': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/changes_to_package_header for more information
  deprecation_warning(
/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/hydra/core/default_element.py:124: UserWarning: In 'callbacks/callbacks_instance_segmentation': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/changes_to_package_header for more information
  deprecation_warning(
/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/hydra/core/default_element.py:124: UserWarning: In 'trainer/trainer600': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/changes_to_package_header for more information
  deprecation_warning(
/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/hydra/core/default_element.py:124: UserWarning: In 'scheduler/onecyclelr': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/changes_to_package_header for more information
  deprecation_warning(
/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/hydra/core/default_element.py:124: UserWarning: In 'optimizer/adamw': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/changes_to_package_header for more information
  deprecation_warning(
/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/hydra/core/default_element.py:124: UserWarning: In 'metrics/miou': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/changes_to_package_header for more information
  deprecation_warning(
/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/hydra/core/default_element.py:124: UserWarning: In 'model/mask3d': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/changes_to_package_header for more information
  deprecation_warning(
/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/hydra/core/default_element.py:124: UserWarning: In 'logging/full': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/changes_to_package_header for more information
  deprecation_warning(
/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/hydra/core/default_element.py:124: UserWarning: In 'data/indoor': Usage of deprecated keyword in package header '# @package _group_'.
See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/changes_to_package_header for more information
  deprecation_warning(
/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
  ret = run_job(
/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/lightning_fabric/utilities/seed.py:39: UserWarning: No seed found, seed set to 3282747009
  rank_zero_warn(f"No seed found, seed set to {seed}")
Global seed set to 3282747009
{'_target_': 'pytorch_lightning.loggers.WandbLogger', 'project': '${general.project_name}', 'name': '${general.experiment_name}', 'save_dir': '${general.save_dir}', 'entity': 'schult', 'resume': 'allow', 'id': '${general.experiment_
name}'}
wandb: Currently logged in as: zjp2023. Use `wandb login --relogin` to force relogin
wandb: ERROR Error while calling W&B API: entity schult not found during upsertBucket (<Response [404]>)
Problem at: /home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/pytorch_lightning/loggers/wandb.py 405 experiment
Error executing job with overrides: ['general.experiment_name=zjp2023_scannet200_val']
Error in call to target 'pytorch_lightning.loggers.wandb.WandbLogger':
CommError('It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networ
king setup.(Error 404: Not Found)')
full_key: logging0

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

**Comment by JonasSchult** [comment]
Hi!
You can change the wandb user [here](https://github.com/JonasSchult/Mask3D/blob/main/conf/logging/full.yaml#L6).

Best,
Jonas

**Comment by xiaotiancai899** [comment]
Thanks a lot!!!

**Comment by TobyZhouWei** [comment]
Hi, my way to solve this problem is to delete " entity: "schult" in Mask3D-main/conf/logging/full.yaml, I find it by accident. I wonder if there is anything wrong with doing this?

**Comment by xiaotiancai899** [comment]
It works. Thanks a lot. And could you give me your Wechat ID? I faced another problem and wonder ask you.

**Comment by TobyZhouWei** [comment]
@xiaotiancai899 I am glad to hear that it does work. I am new in deep learning. How can I give you my Wechat ID privately.

**Comment by xiaotiancai899** [comment]
@TobyZhouWei 我给您发邮件了，163邮箱。
