### ISSUE TITLE
Can 'ignore_class' work in loss_masks?

### ISSUE THREAD

**Issue by Jeff-LiangF** [JonasSchult/Mask3D#68]
Hi @JonasSchult ,

Thanks for your refreshing work! It is a milestone paper in the 3D community.

I am looking at the implications of `ignore_class` during your training. I am assuming that instances with `label == ignore_class` should be totally discarded during training. It is true for [loss_labels](https://github.com/JonasSchult/Mask3D/blob/main/models/criterion.py#L143) because you disable the CE loss for ignore_class. However, it might not hold for [loss_masks](https://github.com/JonasSchult/Mask3D/blob/main/models/criterion.py#L147) where you actually include the [mask loss even for ignore_class](https://github.com/JonasSchult/Mask3D/blob/main/models/criterion.py#L158). 

My conclusion is to the best of my assessment. Let me know your thoughts. Thank you!

**Comment by JonasSchult** [comment]
Hi Jeff! 

Thanks for your kind words! :) 

Your observation is correct. ScanNet also provides masks for semantic classes which are *not* part of the official benchmark, e.g. TV. Therefore, we exclude them from the semantic loss, as we do not want to segment these objects. However, our intuition was that their masks still provide a rich signal, i.e., we can learn from it what an entity might look like, even though it is not evaluated.

However, we found out that including these masks in the loss made little difference to the overall performance...

Best,
Jonas

**Comment by Jeff-LiangF** [comment]
Hi Jonas,

Thanks for getting back to me! Yes, I also tested excluding the masks and got a very slight difference. Thanks!
