### ISSUE TITLE
ModuleNotFoundError: No module named 'datasets.preprocessing'

### ISSUE THREAD

**Issue by bh-cai** [JonasSchult/Mask3D#69]
When I run the command "python datasets/preprocessing/scannet_preprocessing.py preprocess --data_dir="/home/mylabs/Datasets/scannet" --save_dir="/home/mylabs/Datasets/preprocessed/scannet" --git_repo="https://github.com/ScanNet/ScanNet.git" --scannet200=false" for the preprocessing of ScanNet or ScanNet200.I got the error about
 "Traceback (most recent call last):
  File "/home/mylabs/Mask3D/datasets/preprocessing/scannet_preprocessing.py", line 9, in <module>
    from datasets.preprocessing.base_preprocessing import BasePreprocessing
ModuleNotFoundError: No module named 'datasets.preprocessing'"
Can you tell me why the file or model exists but show it is not, and how can I solve this problem, thank you very much!

**Comment by buggogogo** [comment]
I run preprocessing.py in terminal with:
python -m datasets.preprocessing.stpls3d_preprocessing preprocess
--data_dir="/home/zy/3D_Instance_Segmentation/Mask3D/data/raw/stpls3d"
--save_dir="/home/zy/3D_Instance_Segmentation/Mask3D/data/processed/stpls3d"
You can have a try.
