### ISSUE TITLE
Problems about the setup

### ISSUE THREAD

**Issue by JunweiZheng93** [JonasSchult/Mask3D#7]
Hi Jonas. Thx for your great work and effort. I am trying to use your code to do the inference for my own indoor point cloud, which is .ply format. Now I have met some problems.

1. When installing the dependencies according to the README, some errors will pop up. Could you please create a new virtual environment, install all dependencies according to the README and run this [scannet_benchmark.sh](https://github.com/JonasSchult/Mask3D/blob/main/scripts/scannet/scannet_benchmark.sh) script? This workflow will help to find out what the errors are and what stuff still missing.
2. What should I do if I want to do the inference for my own point cloud? Could you give me some advice about how to use your code for the inference?

Looking forward to your reply. Have a nice day!

**Comment by JonasSchult** [comment]
Hi Junwei,

thanks for kind words and interest in our work! :)

> When installing the dependencies according to the README, some errors will pop up. Could you please create a new virtual environment, install all dependencies according to the README and run this [scannet_benchmark.sh](https://github.com/JonasSchult/Mask3D/blob/main/scripts/scannet/scannet_benchmark.sh) script? This workflow will help to find out what the errors are and what stuff still missing.

Can you share your error messages? I will try to help you through the process.

> What should I do if I want to do the inference for my own point cloud? Could you give me some advice about how to use your code for the inference?

That is a great feature extension! Right now, the process would look like to write a preproccesing script similar to these [here](https://github.com/JonasSchult/Mask3D/tree/main/datasets/preprocessing). When I find time, I'll add a direct support for this.
Although this may take a while.

Best,
Jonas

**Comment by JunweiZheng93** [comment]
Hi Jonas. Sorry for my late reply. I have double checked all the necessary dependencies and steps. The reason why I failed is due to my old laptop. There is not enough RAM space when compiling. I worked around by  enlarging the Swap and everything works like charm.

**Comment by JonasSchult** [comment]
Great to hear this! :)
