### ISSUE TITLE
I am sorry that the demo results are still not working perfectly

### ISSUE THREAD

**Issue by TobyZhouWei** [JonasSchult/Mask3D#73]
Hi, I am sorry that the demo results are still not working perfectly. After I upload a ply file, I still receive a blank page like below. There is a another closed issue about this problem before, But I can't get anything useful from the dialogue.

Not Found
The requested URL was not found on this server.

Apache/2.4.41 (Ubuntu) Server at mix3d-demo.nekrasov.dev Port 443

**Comment by JonasSchult** [comment]
We just fixed the demo page :)

Thanks for notifying us.

**Comment by AilsonAir** [comment]
Sadly, I'm having the same issue with the demo page again. o(╥﹏╥)o
