### ISSUE TITLE
Training on ScanNet200: data prepare rRaise an exception

### ISSUE THREAD

**Issue by xiaotiancai899** [JonasSchult/Mask3D#78]
Hi Jonas! This is a fantastic job.
When I train on the scannet dataset, I met a problem about the dataset prepare module. In semseg.py line 194, when the code runs to "self._labels = self._select_correct_labels(labels, num_labels)", there exists an exception. From another issue I know I created the ScanNet200 dataset (with 200 labels) but wanted to train a model for the original ScanNet dataset with 20 labels) on it. But I do not know how to verify in my preprocessing scripts if I enabled scannet200. Could you please show me the detail about it? Thanks a lot！！！

File "/mnt/d/student/Documents/software/wsl/mask3d/mask3d_main/mask3d_main/datasets/semseg.py", line 194, in __init__
    self._labels = self._select_correct_labels(labels, num_labels)
  File "/mnt/d/student/Documents/software/wsl/mask3d/mask3d_main/mask3d_main/datasets/semseg.py", line 595, in _select_correct_labels
    raise ValueError(msg)
ValueError: not available number labels, select from:
            200, 200

**Comment by JonasSchult** [comment]
Hi!

Thanks for your interest in our work! :)

You can set `--scannet200=false` to create a dataset with 20 labels (see [here](https://github.com/JonasSchult/Mask3D/blob/main/scripts/scannet200/scannet200_val.sh)).

Best,
Jonas
