### ISSUE TITLE
How to train mask3d on scannet200 dataset?

### ISSUE THREAD

**Issue by xiaotiancai899** [JonasSchult/Mask3D#79]
How to train mask3d on scannet200 dataset?

**Comment by Wang-pengfei** [comment]
哥们你可以在scannet200上跑实验了吗

**Comment by xiaotiancai899** [comment]
@JonasSchult @francisengelmann @eltociear

**Comment by JonasSchult** [comment]
Hi!

Thanks for your interest in our work! :)

Take a look [here](https://github.com/JonasSchult/Mask3D/blob/main/scripts/scannet200/scannet200_val.sh).

Best,
Jonas
