### ISSUE TITLE
Preprocessing on Scannet

### ISSUE THREAD

**Issue by xjdexjt** [JonasSchult/Mask3D#8]
![image](https://user-images.githubusercontent.com/40589000/194745170-f9306442-c242-45fa-91b9-546cdb858146.png)
When I run the processing code for scannet, the following results is obtained.
![image](https://user-images.githubusercontent.com/40589000/194745234-2e4cd926-84e2-4a78-b6f6-34fa39c9de06.png)
![image](https://user-images.githubusercontent.com/40589000/194745269-305d4c27-3898-4f23-84a8-022e73e00f26.png)
Then, the code is finished, and the data is not processed.

Besides, I check the code, but I cannot find any processing functions are used in "__init__". 
![image](https://user-images.githubusercontent.com/40589000/194745341-1efaa265-da8a-492d-8775-9e41d146211a.png)
Could you give me any advice on how to processing the data.

Thanks.

**Comment by xjdexjt** [comment]
OK, I solved.
Thanks for your great work.

**Comment by JonasSchult** [comment]
Hi!
Which problem do you face?

Best,
Jonas

**Comment by Mythili-kannan** [comment]
![image](https://user-images.githubusercontent.com/67571832/195835974-af07adf3-e998-4004-9e08-c0518d4c3884.png)
while running s3dis_preprocessing.py  i got just this screen, can you please let me know how to proceed further.

Thanks in advance

**Comment by JonasSchult** [comment]
Hi!
You miss the command `preprocess` when calling `s3dis_preprocessing.py`.

```
                                                 |
                                                 v
datasets/preprocessing/s3dis_preprocessing.py preprocess \
--data_dir="PATH_TO_Stanford3dDataset_v1.2" \
--save_dir="../../data/processed/s3dis"
```

Let me know if this solves your problem :)

Best,
Jonas

**Comment by Mythili-kannan** [comment]
got it thank you so much, one more doubt is there is any inference script which will take single .ply and gives out instances , it will be very helpful

**Comment by Mythili-kannan** [comment]
getting this error when i run script of preprocessing of s3dis 
FILE SIZE DOES NOT MATCH FOR /home/sai/mythili_wd/Segmentation/Mask3D/Stanford3dDataset_v1.2_Aligned_Version/Area_5/lobby_1/lobby_1.txt
(1162766 vs. 1223

**Comment by JonasSchult** [comment]
> got it thank you so much will try them, one more doubt is there is any inference script which will take single .ply and gives out instances , it will be very helpful

totally agree! #11 deals with this, already. Will take some time for this :)


> getting this error when i run script of preprocessing of s3dis FILE SIZE DOES NOT MATCH FOR /home/sai/mythili_wd/Segmentation/Mask3D/Stanford3dDataset_v1.2_Aligned_Version/Area_5/lobby_1/lobby_1.txt (1162766 vs. 1223236)

this is only a debug message. You can ignore it.

**Comment by Mythili-kannan** [comment]
ValueError: the number of columns changed from 6 to 5 at row 180389; use `usecols` to select a subset and avoid this error

Thanks for the reply ,but at the end its showing error for Area_5 of s3dis

**Comment by JonasSchult** [comment]
Interesting! I will take a look into this tomorrow. Thanks for letting me know!

**Comment by Mythili-kannan** [comment]
Thank you waiting for the reply!!

**Comment by JonasSchult** [comment]
I figured out what went wrong. Thank you very much for bringing it to my attention! :)

There is a coding error in `Area_5/hallway_6/Annotations/ceiling_1.txt` in line `180389`.
![coding_error](https://user-images.githubusercontent.com/9321037/195952254-50bcdd26-53d9-4025-89f4-86ea5340e657.png)
**I just deleted the bad character. That solved the issue.**

Moreover, you need to rename `Area_6/copyRoom_1/copy_Room_1.txt` to `Area_6/copyRoom_1/copyRoom_1.txt` as it breaks the naming convention.

I fixed these issues early in the project and forgot about describing them in the README. I will adapt the s3dis preprocessing script that it won't cause trouble in the future.

Thanks again! :)

**Comment by Mythili-kannan** [comment]
Thanks for the reply, now getting this error, can you please help me here

    color_std.append(sample["color_std"])
    │         │      └ 'mean'
    │         └ <method 'append' of 'list' objects>
    └ []

TypeError: string indices must be integers

**Comment by JonasSchult** [comment]
Here is the [test script for S3DIS](https://github.com/JonasSchult/Mask3D/blob/main/scripts/s3dis/s3dis_from_scratch.sh#L21).
I will make it a bit clearer in the readme ;)

**Comment by Mythili-kannan** [comment]
Thank you so much for the guidance :)

**Comment by Mythili-kannan** [comment]
Hi can you please help me here,
after i ran
 python main_instance_segmentation.py general.project_name="s3dis_eval" general.checkpoint="path to checkpoint of area 1 which you provided in the readme" general.train_mode=false data/datasets=s3dis 
 
 this is how my terminal looks 
 
 GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
generate data/processed/s3dis/train_Area_5_database.yaml first
wandb: Waiting for W&B process to finish... (success).
wandb: You can sync this run to the cloud by running:
wandb: wandb sync saved/DEBUG_ABLATION/wandb/offline-run-20221016_194819-DEBUG_ABLATION
wandb: Find logs at: saved/DEBUG_ABLATION/wandb/offline-run-20221016_194819-DEBUG_ABLATION/logs

there is one folder created called saved but its having only logs, where can i find results

**Comment by xjdexjt** [comment]
Which S3DIS version do you use?
Stanford3dDataset_v1.2_Aligned_Version or Stanford3dDataset_v1.2?
Thanks.
@JonasSchult

**Comment by Mythili-kannan** [comment]
Yes thats correct

**Comment by xjdexjt** [comment]
![b59ec14d3bf457e809536978df89944](https://user-images.githubusercontent.com/40589000/196126504-ebe0ded9-fa45-4d4a-88a5-d690658deb9d.jpg)
By the way, when I run the training code of S3DIS generated from Stanford3dDataset_v1.2_Aligned_Version, I met this error.
The "downsampling" is not defined in general configuration.
When I remove the "downsampling" in "s3dis.yaml", the training code run successfully.
Could you tell me if I need remove the "downsampling" or I need define the value of "downsampling"?
![image](https://user-images.githubusercontent.com/40589000/196127035-12962bdb-e7c7-411b-b35b-684d75b9033a.png)

**Comment by JonasSchult** [comment]
Hi,

please pull the latest version of the codebase. The downsampling parameter is deprecated.

We use `Stanford3dDataset_v1.2`, not the aligned version. :)

> Hi can you please help me here,after i get generated output in eval_output folder, how can i apply the instance on the individual pointcloud

The evaluation will be automatically started and outputs the results. Or did you mean how to get the visualizations?
Try the parameter `general.save_visualizations=true`.

Best
Jonas

**Comment by lizOnly** [comment]
Hi, 
I would greatly appreciate it if you could help me with this.
I face this problem when preprocessing S3DIS 
**ValueError: could not convert string '103.0\x100000' to float64 at row 323473, column 6.**

Here is the whole error

2022-10-25 11:26:16.548 | INFO     | datasets.preprocessing.base_preprocessing:preprocess:45 - Tasks for Area_5: 68
[Parallel(n_jobs=16)]: Using backend LokyBackend with 16 concurrent workers.
[Parallel(n_jobs=16)]: Done   9 tasks      | elapsed:    5.3s
[Parallel(n_jobs=16)]: Done  18 tasks      | elapsed:    8.0s
[Parallel(n_jobs=16)]: Done  29 tasks      | elapsed:    9.6s
[Parallel(n_jobs=16)]: Done  44 out of  68 | elapsed:   12.9s remaining:    7.0s
FILE SIZE DOES NOT MATCH FOR /mnt/DATA/data_indoor/Stanford3dDataset_v1.2/Area_5/office_36/office_36.txt
(1301245 vs. 1231999)
[Parallel(n_jobs=16)]: Done  51 out of  68 | elapsed:   15.2s remaining:    5.1s
[Parallel(n_jobs=16)]: Done  58 out of  68 | elapsed:   16.3s remaining:    2.8s
[Parallel(n_jobs=16)]: Done  65 out of  68 | elapsed:   16.4s remaining:    0.8s
2022-10-25 11:26:33.168 | ERROR    | fire.core:_CallAndUpdateTrace:681 - An error has been caught in function '_CallAndUpdateTrace', process 'MainProcess' (22595), thread 'MainThread' (140371701749568):
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/lizeth/.local/lib/python3.10/site-packages/joblib/externals/loky/process_executor.py", line 436, in _process_worker
    r = call_item()
  File "/home/lizeth/.local/lib/python3.10/site-packages/joblib/externals/loky/process_executor.py", line 288, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/lizeth/.local/lib/python3.10/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/home/lizeth/.local/lib/python3.10/site-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/home/lizeth/.local/lib/python3.10/site-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/mnt/Chest/Repositories/Mask3D/datasets/preprocessing/s3dis_preprocessing.py", line 111, in process_file
    instance_points = np.loadtxt(instance.path)
  File "/home/lizeth/miniconda3/envs/mask3d/lib/python3.10/site-packages/numpy/lib/npyio.py", line 1318, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
  File "/home/lizeth/miniconda3/envs/mask3d/lib/python3.10/site-packages/numpy/lib/npyio.py", line 979, in _read
    arr = _load_from_filelike(
ValueError: could not convert string '103.0\x100000' to float64 at row 323473, column 6.
"""

**Comment by JonasSchult** [comment]
I will close the issue for now. If some problems still exist, please re-open it! :)

Best,
Jonas

**Comment by MarcoAyman** [comment]
I downloaded the dataset (Stanford3dDataset_v1.2) but when i am trying to use the script i get a strange error and its not running 


C:\Users\mhanna\Desktop\S3DIS_preprocessing>python s3dis_preprocessing.py preprocess --data_dir=C:\Users\mhanna\Desktop\S3DIS_preprocessing\data\raw\Stanford3dDataset_v1.2 --save_dir=C:\Users\mhanna\Desktop\S3DIS_preprocessing\data\processed\s3dis --n_jobs=-1
2023-12-13 15:32:51.176 | INFO     | base_preprocessing:preprocess:47 - Tasks for Area_1: 44
[Parallel(n_jobs=12)]: Using backend LokyBackend with 12 concurrent workers.
2023-12-13 15:32:53.891 | ERROR    | fire.core:_CallAndUpdateTrace:691 - An error has been caught in function '_CallAndUpdateTrace', process 'MainProcess' (13104), thread 'MainThread' (27656):
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\python\lib\site-packages\joblib\externals\loky\process_executor.py", line 463, in _process_worker
    r = call_item()
  File "C:\python\lib\site-packages\joblib\externals\loky\process_executor.py", line 291, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "C:\python\lib\site-packages\joblib\parallel.py", line 589, in __call__
    return [func(*args, **kwargs)
  File "C:\python\lib\site-packages\joblib\parallel.py", line 589, in <listcomp>
    return [func(*args, **kwargs)
  File "C:\Users\mhanna\Desktop\S3DIS_preprocessing\s3dis_preprocessing.py", line 151, in process_file
    pcd_size = self._buf_count_newlines_gen(os.path.join(filepath, scene_name, "Annotations", f"{scene_name}.txt"))
  File "C:\Users\mhanna\Desktop\S3DIS_preprocessing\s3dis_preprocessing.py", line 92, in _buf_count_newlines_gen
    with open(fname, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\mhanna\\Desktop\\S3DIS_preprocessing\\data\\raw\\Stanford3dDataset_v1.2\\Area_1\\hallway_4.txt'
"""


The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "C:\Users\mhanna\Desktop\S3DIS_preprocessing\s3dis_preprocessing.py", line 283, in <module>
    Fire(S3DISPreprocessing)
    │    └ <class '__main__.S3DISPreprocessing'>
    └ <function Fire at 0x000001DD1DC770A0>

  File "C:\python\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      │     │          │     │                 │        └ 's3dis_preprocessing.py'
                      │     │          │     │                 └ {}
                      │     │          │     └ Namespace(verbose=False, interactive=False, separator='-', completion=None, help=False, trace=False)
                      │     │          └ ['preprocess', '--data_dir=C:\\Users\\mhanna\\Desktop\\S3DIS_preprocessing\\data\\raw\\Stanford3dDataset_v1.2', '--save_dir=C...
                      │     └ <class '__main__.S3DISPreprocessing'>
                      └ <function _Fire at 0x000001DD1E01DC60>

  File "C:\python\lib\site-packages\fire\core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
    │                           └ <function _CallAndUpdateTrace at 0x000001DD1E01DD80>
    └ <bound method BasePreprocessing.preprocess of <__main__.S3DISPreprocessing object at 0x000001DD1EC4BFA0>>

> File "C:\python\lib\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                │   │          └ {}
                │   └ []
                └ <bound method BasePreprocessing.preprocess of <__main__.S3DISPreprocessing object at 0x000001DD1EC4BFA0>>

  File "C:\Users\mhanna\Desktop\S3DIS_preprocessing\base_preprocessing.py", line 48, in preprocess
    parallel_results = Parallel(n_jobs=self.n_jobs, verbose=10)(
                       │               │    └ 12
                       │               └ <__main__.S3DISPreprocessing object at 0x000001DD1EC4BFA0>
                       └ <class 'joblib.parallel.Parallel'>

  File "C:\python\lib\site-packages\joblib\parallel.py", line 1952, in __call__
    return output if self.return_generator else list(output)
           │         │    │                          └ <generator object Parallel._get_outputs at 0x000001DD1ECF9D20>
           │         │    └ False
           │         └ Parallel(n_jobs=12)
           └ <generator object Parallel._get_outputs at 0x000001DD1ECF9D20>

  File "C:\python\lib\site-packages\joblib\parallel.py", line 1595, in _get_outputs
    yield from self._retrieve()
               │    └ <function Parallel._retrieve at 0x000001DD1EC91630>
               └ Parallel(n_jobs=12)

  File "C:\python\lib\site-packages\joblib\parallel.py", line 1699, in _retrieve
    self._raise_error_fast()
    │    └ <function Parallel._raise_error_fast at 0x000001DD1EC916C0>
    └ Parallel(n_jobs=12)

  File "C:\python\lib\site-packages\joblib\parallel.py", line 1734, in _raise_error_fast
    error_job.get_result(self.timeout)
    │         │          │    └ None
    │         │          └ Parallel(n_jobs=12)
    │         └ <function BatchCompletionCallBack.get_result at 0x000001DD1EC90790>
    └ <joblib.parallel.BatchCompletionCallBack object at 0x000001DD1ED0F5E0>

  File "C:\python\lib\site-packages\joblib\parallel.py", line 736, in get_result
    return self._return_or_raise()
           │    └ <function BatchCompletionCallBack._return_or_raise at 0x000001DD1EC90820>
           └ <joblib.parallel.BatchCompletionCallBack object at 0x000001DD1ED0F5E0>

  File "C:\python\lib\site-packages\joblib\parallel.py", line 754, in _return_or_raise
    raise self._result
          └ <joblib.parallel.BatchCompletionCallBack object at 0x000001DD1ED0F5E0>

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\mhanna\\Desktop\\S3DIS_preprocessing\\data\\raw\\Stanford3dDataset_v1.2\\Area_1\\hallway_4.txt'

**Comment by homee-lion** [comment]
There are two things:
- The first thing is that the error described [here](https://github.com/JonasSchult/Mask3D/issues/8#issuecomment-1279535948) only appears in the "Aligned_Version".
- After following the [steps](https://github.com/JonasSchult/Mask3D/issues/8#issuecomment-1279535948) to fix the encoding error and file naming error, I still got the following error:
```
FILE SIZE DOES NOT MATCH FOR input_data/s3dis/Stanford3dDataset_v1.2_Aligned_Version/Area_5/lobby_1/lobby_1.txt
(1162766 vs. 1223236)
```

**Comment by lionlai1989** [comment]
There are two things:
- The first thing is that the error described [here](https://github.com/JonasSchult/Mask3D/issues/8#issuecomment-1279535948) only appears in the "Aligned_Version".
- After following the [steps](https://github.com/JonasSchult/Mask3D/issues/8#issuecomment-1279535948) to fix the encoding error and file naming error, I still got the following error:
```
2024-05-22 03:40:22.826 | INFO     | datasets.preprocessing.base_preprocessing:preprocess:47 - Tasks for Area_5: 68
[Parallel(n_jobs=8)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done   2 tasks      | elapsed:    2.8s
[Parallel(n_jobs=8)]: Done   9 tasks      | elapsed:    9.2s
FILE SIZE DOES NOT MATCH FOR input_data/s3dis/Stanford3dDataset_v1.2_Aligned_Version/Area_5/lobby_1/lobby_1.txt
(1162766 vs. 1223236)
```

Please help me to fix it.

**Comment by Yitao-Lu** [comment]
> I figured out what went wrong. Thank you very much for bringing it to my attention! :)
> 
> There is a coding error in `Area_5/hallway_6/Annotations/ceiling_1.txt` in line `180389`. ![coding_error](https://user-images.githubusercontent.com/9321037/195952254-50bcdd26-53d9-4025-89f4-86ea5340e657.png) **I just deleted the bad character. That solved the issue.**
> 
> Moreover, you need to rename `Area_6/copyRoom_1/copy_Room_1.txt` to `Area_6/copyRoom_1/copyRoom_1.txt` as it breaks the naming convention.
> 
> I fixed these issues early in the project and forgot about describing them in the README. I will adapt the s3dis preprocessing script that it won't cause trouble in the future.
> 
> Thanks again! :)

Thank GOD! You're my hero!

**Comment by anbaoxu1** [comment]
您好，您可以帮助我吗？
[Parallel(n_jobs=32)]: Using backend LokyBackend with 32 concurrent workers.
2024-10-25 20:24:13.181 | ERROR    | fire.core:_CallAndUpdateTrace:684 - An error has been caught in function '_CallAndUpdateTrace', process 'MainProcess' (157297), thread 'MainThread' (139900515624768):
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/xu/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/joblib/externals/loky/process_executor.py", line 463, in _process_worker
    r = call_item()
  File "/home/xu/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/joblib/externals/loky/process_executor.py", line 291, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/xu/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/joblib/parallel.py", line 598, in __call__
    return [func(*args, **kwargs)
  File "/home/xu/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/joblib/parallel.py", line 598, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/xu/abx/mask3d/datasets/preprocessing/s3dis_preprocessing.py", line 153, in process_file
    points = np.vstack(scene_points)
  File "/home/xu/anaconda3/envs/mask3d_cuda113/lib/python3.10/site-packages/numpy/core/shape_base.py", line 289, in vstack
    return _nx.concatenate(arrs, 0, dtype=dtype, casting=casting)
ValueError: need at least one array to concatenate
"""
The above exception was the direct cause of the following exception:
当前存在这个问题
