### ISSUE TITLE
A error during training on the ScanNet200 dataset

### ISSUE THREAD

**Issue by xiaotiancai899** [JonasSchult/Mask3D#81]
The command line is 'python main_instance_segmentation.py' when training on the ScanNet200 dataset, and error is as the following:

/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/accelerator_connector.py:446: LightningDeprecationWarning: Setting `Trainer(gpus=1)` is deprecated in v1.7 and will be removed in
 v2.0. Please use `Trainer(accelerator='gpu', devices=1)` instead.
  rank_zero_deprecation(
/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py:52: LightningDeprecationWarning: Setting `Trainer(resume_from_checkpoint=)` is deprecated in v1.5 and wil
l be removed in v1.7. Please pass `Trainer.fit(ckpt_path=)` directly instead.
  rank_zero_deprecation(
/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/callback_connector.py:57: LightningDeprecationWarning: Setting `Trainer(weights_save_path=)` has been deprecated in v1.6 and will
 be removed in v1.8. Please pass ``dirpath`` directly to the `ModelCheckpoint` callback
  rank_zero_deprecation(
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py:733: LightningDeprecationWarning: `trainer.resume_from_checkpoint` is deprecated in v1.5 and will be removed in v2.0. Specify the
 fit checkpoint path with `trainer.fit(ckpt_path=)` instead.
  ckpt_path = ckpt_path or self.resume_from_checkpoint
/mnt/d/student/Documents/software/wsl/mask3d/mask3d_main/mask3d_main/datasets/semseg.py:578: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/
load for full details.
  file = yaml.load(f)
/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:616: UserWarning: Checkpoint directory /mnt/d/student/Documents/software/wsl/mask3d/mask3d_main/mask3d_main/saved/zjp_
scannet200_val exists and is not empty.
  rank_zero_warn(f"Checkpoint directory {dirpath} exists and is not empty.")
Restoring states from the checkpoint path at saved/zjp_scannet200_val/last-epoch.ckpt
Traceback (most recent call last):
  File "/mnt/d/student/Documents/software/wsl/mask3d/mask3d_main/mask3d_main/main_instance_segmentation.py", line 106, in main
    train(cfg)
  File "/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/hydra/main.py", line 27, in decorated_main
    return task_function(cfg_passthrough)
  File "/mnt/d/student/Documents/software/wsl/mask3d/mask3d_main/mask3d_main/main_instance_segmentation.py", line 85, in train
    runner.fit(model)
  File "/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 696, in fit
    self._call_and_handle_interrupt(
  File "/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 737, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1112, in _run
    self._restore_modules_and_callbacks(ckpt_path)
  File "/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1067, in _restore_modules_and_callbacks
    self._checkpoint_connector.restore_model()
  File "/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 182, in restore_model
    self.trainer.strategy.load_model_state_dict(self._loaded_checkpoint)
  File "/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 343, in load_model_state_dict
    self.lightning_module.load_state_dict(checkpoint["state_dict"])
  File "/home/clinton/anaconda3/envs/mask_3d/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for InstanceSegmentation:
        Missing key(s) in state_dict: "criterion.empty_weight".

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

How to solve this problem? Thanks a lot !!!!!!

**Comment by xiaotiancai899** [comment]
@JonasSchult @eltociear

**Comment by JonasSchult** [comment]
Hi!

Can you share the script for starting the training?

Best,
Jonas

**Comment by xiaotiancai899** [comment]
> Hi!
> 
> Can you share the script for starting the training?
> 
> Best, Jonas

python main_instance_segmentation
.py \general.checkpoint='checkpoints/scannet200/scannet200_val.ckpt' \general.train_mode=false

**Comment by JonasSchult** [comment]
That is a strange error.
We recently released a fix for the virtual environment. I would recommend to try the following:
1. re-install the environment as described in the readme. (Please pull the project first)
2. delete the `saved/` 
3. rerun the evaluation

Please let me know if the error continues to occur.

Best,
Jonas

**Comment by xiaotiancai899** [comment]
Currently I run the command as 'python main_instance_segmentation
.py \general.checkpoint='checkpoints/scannet200/scannet200_val.ckpt' \general.train_mode=false'.
And I get this result, the following shows the last part of it, which I believe is a little bit low average score. 
Also, I do not find the checkpoint file in the 'saved' folder. Any ideas? Thanks in advance!!!

coat rack      :          0.000          0.000          0.000
storage organizer:            nan            nan            nan
folded chair   :          0.000          0.000          0.000
fire alarm     :            nan            nan            nan
power strip    :            nan            nan            nan
calendar       :          0.000          0.000          0.000
poster         :          0.000          0.000          0.000
potted plant   :          0.000          0.000          0.083
luggage        :            nan            nan            nan
mattress       :          0.000          0.000          0.000
----------------------------------------------------------------
average        :          0.171          0.297          0.389


> That is a strange error. We recently released a fix for the virtual environment. I would recommend to try the following:
> 
> 1. re-install the environment as described in the readme. (Please pull the project first)
> 2. delete the `saved/`
> 3. rerun the evaluation
> 
> Please let me know if the error continues to occur.
> 
> Best, Jonas

**Comment by JonasSchult** [comment]
Hi! :)
As you evaluate the model, we do not save the checkpoint.

Moreover, you should run the model like [this](https://github.com/JonasSchult/Mask3D/blob/main/scripts/scannet200/scannet200_val.sh#L19).

Best,
Jonas

**Comment by JonasSchult** [comment]
only running `python main_instance_segmentation.py` is not sufficient. Take a look [here](https://github.com/JonasSchult/Mask3D/tree/main/scripts) for a few examples of how to train and evaluate. :)

Best,
Jonas

**Comment by xiaotiancai899** [comment]
python main_instance_segmentation.py \
general.experiment_name="scannet200_val" \
general.project_name="scannet200" \
data/datasets=scannet200 \
general.num_targets=201 \
data.num_labels=200 \
general.eval_on_segments=true \
general.train_on_segments=true

Is it sufficient?

**Comment by JonasSchult** [comment]
To reproduce our results:
```
#!/bin/bash
export OMP_NUM_THREADS=3  # speeds up MinkowskiEngine

CURR_DBSCAN=0.95
CURR_TOPK=750
CURR_QUERY=150

# TEST
python main_instance_segmentation.py \
general.experiment_name="reproduce_scannet200_val_query_${CURR_QUERY}_topk_${CURR_TOPK}_dbscan_${CURR_DBSCAN}" \
general.project_name="scannet200_eval" \
general.checkpoint="checkpoints/scannet200/scannet200_val.ckpt" \
data/datasets=scannet200 \
general.num_targets=201 \
data.num_labels=200 \
general.eval_on_segments=true \
general.train_on_segments=true \
general.train_mode=false \
model.num_queries=${CURR_QUERY} \
general.topk_per_image=${CURR_TOPK} \
general.use_dbscan=true \
general.dbscan_eps=${CURR_DBSCAN}
```

A leaner version without expensive postprocessing:
```
python main_instance_segmentation.py \
general.experiment_name="leaner_version_scannet200_val" \
general.project_name="scannet200_eval" \
general.checkpoint="checkpoints/scannet200/scannet200_val.ckpt" \
data/datasets=scannet200 \
general.num_targets=201 \
data.num_labels=200 \
general.eval_on_segments=true \
general.train_on_segments=true \
general.train_mode=false
```

**Comment by xiaotiancai899** [comment]
> To reproduce our results:
> 
> ```
> #!/bin/bash
> export OMP_NUM_THREADS=3  # speeds up MinkowskiEngine
> 
> CURR_DBSCAN=0.95
> CURR_TOPK=750
> CURR_QUERY=150
> 
> # TEST
> python main_instance_segmentation.py \
> general.experiment_name="reproduce_scannet200_val_query_${CURR_QUERY}_topk_${CURR_TOPK}_dbscan_${CURR_DBSCAN}" \
> general.project_name="scannet200_eval" \
> general.checkpoint="checkpoints/scannet200/scannet200_val.ckpt" \
> data/datasets=scannet200 \
> general.num_targets=201 \
> data.num_labels=200 \
> general.eval_on_segments=true \
> general.train_on_segments=true \
> general.train_mode=false \
> model.num_queries=${CURR_QUERY} \
> general.topk_per_image=${CURR_TOPK} \
> general.use_dbscan=true \
> general.dbscan_eps=${CURR_DBSCAN}
> ```
> 
> A leaner version without expensive postprocessing:
> 
> ```
> python main_instance_segmentation.py \
> general.experiment_name="leaner_version_scannet200_val" \
> general.project_name="scannet200_eval" \
> general.checkpoint="checkpoints/scannet200/scannet200_val.ckpt" \
> data/datasets=scannet200 \
> general.num_targets=201 \
> data.num_labels=200 \
> general.eval_on_segments=true \
> general.train_on_segments=true \
> general.train_mode=false
> ```

Thanks very much!!! By the way, how to postprocessing?

**Comment by JonasSchult** [comment]
DBSCAN is an optional step which takes quite some time. You can enable/disable it like this: `general.use_dbscan=true/false`.

Hope I could help you :)

**Comment by xiaotiancai899** [comment]
Very helpful!!! Thanks a lot !!!

**Comment by xiaotiancai899** [comment]
> 

This is for test? But I wannd do training. What is the command should I use?
