### ISSUE TITLE
 No such file or directory on s3dis

### ISSUE THREAD

**Issue by hj2532006916** [JonasSchult/Mask3D#84]
![image](https://github.com/JonasSchult/Mask3D/assets/133661066/3e09eff1-168e-4de9-8e86-ad9c3c9fca86)

**Comment by JonasSchult** [comment]
Hi!

Thanks for your interest in our work! :)

The latest version of Mask3D should fix this issue. Just pull the latest version.

Please reopen the issue if the problem remains.

Best,
Jonas
