### ISSUE TITLE
ModuleNotFoundError: No module named 'datasets'

### ISSUE THREAD

**Issue by hj2532006916** [JonasSchult/Mask3D#85]
![image](https://github.com/JonasSchult/Mask3D/assets/133661066/aaff26ff-5808-4cc5-8541-8492523eba63)
who can give me some suggestions 。Thanks

**Comment by LinLin1031** [comment]
Just change "from datasets.preprocessing.base_preprocessing import BasePreprocessing" in line 7 of "s3dis_preprocessing.py" to "from base_preprocessing import BasePreprocessing" will solve the problem.

**Comment by LinLin1031** [comment]
It is simply a matter of relative paths.

**Comment by hj2532006916** [comment]
Thank you for your reply, but I still can't run it. It seems that datasets have not been loaded into my environment. Can you give me some advice? Thank you. Please refer to the following figure for details
![image](https://github.com/JonasSchult/Mask3D/assets/133661066/3a3b7174-db4f-4e5e-bbe0-a9c1fe4a81e9)

**Comment by binsch** [comment]
If you look at the path you can see that it should be `python -m datasets.preprocessing.s3dis_preprocessing ...`.

**Comment by hj2532006916** [comment]
Thank you for your help. If you could give me your contact information, we can communicate in the future.
