### ISSUE TITLE
could not convert string '103.0\x100000' to float64 at row 323473, column 6. how to solve

### ISSUE THREAD

**Issue by hj2532006916** [JonasSchult/Mask3D#87]
![image](https://github.com/JonasSchult/Mask3D/assets/133661066/f3114044-ef16-486b-8413-e02d275b5eba)

**Comment by hj2532006916** [comment]
@JonasSchult  Can you help me？

**Comment by HirofumiMatsuda** [comment]
@hj2532006916 
I solved this error by modifying Line 323474 in `Stanford3dDataset_v1.2/Area_5/office_19/Annotations/ceiling_1.txt`.

https://github.com/zeliu98/CloserLook3D/issues/15

**Comment by hj2532006916** [comment]
Thank you for your reply. Your answer perfectly solved my problem. Thank you！！！！
