### ISSUE TITLE
 Waiting for W&B process to finish... (success).

### ISSUE THREAD

**Issue by bh-cai** [JonasSchult/Mask3D#89]
![1684743516729](https://github.com/JonasSchult/Mask3D/assets/58178860/6f925c7f-ad55-41f5-9dfd-97f0909b804c)
Dear sir,
When I train by the "main_instance_segmentation.py general.experiment_name=Run-1_validation general.eval_on_segments=true general.train_on_segments=true", I got the result above, but don't understand what it means? Do you know if my training was successful? If not, how can I see the signs of success?  Thank you very much!

**Comment by JonasSchult** [comment]
Hi! :)

Thanks for your interest in our work!

It seems like you didnt create the ScanNet dataset first (see [here](https://github.com/JonasSchult/Mask3D#scannet--scannet200)).

Please reopen the issue if the problem remains.

Best,
Jonas
