### ISSUE TITLE
I have some problems on s3dis

### ISSUE THREAD

**Issue by hj2532006916** [JonasSchult/Mask3D#90]
![image](https://github.com/JonasSchult/Mask3D/assets/133661066/5ab6e335-62ca-41f1-b281-ba808d8f7d08)
can you give me some suggestions!Thanks a lot!

**Comment by JonasSchult** [comment]
Hi! :)

You can correct the S3DIS dataset like [this](https://github.com/JonasSchult/Mask3D/issues/8).

Best,
Jonas

**Comment by Bindusara** [comment]
I also faced the same problem, I was able to solve it by deleting the additional 'wall_3 (1)' file in the Annotations from Area_5/office_36/Annotations.
