### ISSUE TITLE
A drop in performance when training without segments

### ISSUE THREAD

**Issue by chunfeng3364** [JonasSchult/Mask3D#92]
Hi! 

Thanks for the great work! I have a question about training with segments for Scannet200. I tried training Mask3D on Scannet200 without point2segment by setting general.train_on_segments and general.eval_on_segments to False. I saw a big drop in performance on the validation set, from AP 64.8 to AP 53.2. I also tried Mask3D on another dataset called SR3D and saw a similar drop in performance. Is this performance difference between the two settings expected?  

Would love to hear your thoughts and insights. Thank you!

**Comment by xiaodongww** [comment]
Hi, how much time does training ScanNet200 without segments in your experiments cost? I test the authors' model with `general.eval_on_segments` set to false and the evaluation process becomes quite long and takes about 2h. In view of this, the training time will become unacceptably long.

**Comment by JonasSchult** [comment]
Hi!

> evaluation process becomes quite long and takes about 2h

Usually, evaluation on segments gives only a minor boost in speed. Could it be the case that you enabled DBSCAN? It takes quite long.

>  I saw a big drop in performance on the validation set

Evaluating on segments does in fact help quite a lot on certain datasets. :)

Best,
Jonas

**Comment by JonasSchult** [comment]
I close the issue for now. Please reopen it if you have further questions :)

**Comment by chunfeng3364** [comment]
Thanks for your reply! 

Could you please tell me the specific settings in your experiments about this? I use the Scannet dataset with full classes, which is "data/datasets=scannet200" in Mask3D configs. And I see a big drop in performance on the validation set. In your settings, in what dataset do the segments help a lot? What is the performance like when you don't use segments in training and evaluating? 

Would love to hear your thoughts and insights! Thank you!
